"""empty message

Revision ID: 08adb3d62e80
Revises: 25afaa270b96
Create Date: 2022-08-22 15:08:07.357882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08adb3d62e80'
down_revision = '25afaa270b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('key', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_keys')
    # ### end Alembic commands ###
