"""empty message

Revision ID: 676e071b9d16
Revises: 08adb3d62e80
Create Date: 2022-08-22 15:11:18.944857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676e071b9d16'
down_revision = '08adb3d62e80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'api_keys', ['key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api_keys', type_='unique')
    # ### end Alembic commands ###
